import * as source from './source';
import * as destination from './destination';
import * as automate from './automate';
import * as channelSplitter from './channel-splitter';
import * as debug from './debug';
import * as channelMerger from './channel-merger';
import * as adsr from './adsr';
import * as gain from './gain';
import * as metronome from './metronome';
import * as moogEffect from './moog';
import * as bitcrusherEffect from './bitcrusher';
import * as biquadFilter from './biquad-filter';
import * as delayEffect from './delay';
import * as dynamicsCompressor from './dynamics-compressor';
import * as chorusEffect from './chorus';
import * as overdriveEffect from './overdrive';
import * as audioBuffer from './audio-buffer-source';
import * as convolver from './convolver';
import * as tremoloEffect from './tremolo';
import * as pingPong from './ping-pong-delay';
import * as stereoPanner from './stereo-panner';
import * as spatialPanner from './spatial-panner';
import * as noise from './noise';
import * as oscillator from './oscillator';
import * as microphone from './microphone';
import * as distorter from './distorter';
import * as equalizer from './equalizer';
import * as frequencyAnalyser from './frequency-analyser';
import * as waveformAnalyser from './waveform-analyser';
import * as spectrogramAnalyser from './spectrogram-analyser';

export namespace StandardNodes.Audio {
  export import Source = source.Source;
  export import Destination = destination.Destination;
  export import Automate = automate.Automate;
  export import ChannelSplitter = channelSplitter.ChannelSplitter;
  export import Debug = debug.Debug;
  export import ChannelMerger = channelMerger.ChannelMerger;
  export import ADSR = adsr.ADSR;
  export import Gain = gain.Gain;
  export import Metronome = metronome.Metronome;
  export import MoogEffect = moogEffect.MoogEffect;
  export import BitcrusherEffect = bitcrusherEffect.BitcrusherEffect;
  export import BiquadFilter = biquadFilter.BiquadFilter;
  export import DelayEffect = delayEffect.DelayEffect;
  export import DynamicsCompressor = dynamicsCompressor.DynamicsCompressor;
  export import ChorusEffect = chorusEffect.ChorusEffect;
  export import OverdriveEffect = overdriveEffect.OverdriveEffect;
  export import AudioBufferSource = audioBuffer.AudioBufferSource;
  export import Convolver = convolver.Convolver;
  export import TremoloEffect = tremoloEffect.TremoloEffect;
  export import PingPongDelay = pingPong.PingPongEffect;
  export import StereoPanner = stereoPanner.StereoPanner;
  export import SpatialPanner = spatialPanner.SpatialPanner;
  export import Noise = noise.Noise;
  export import Oscillator = oscillator.Oscillator;
  export import Microphone = microphone.Microphone;
  export import Distorter = distorter.Distorter;
  export import Equalizer = equalizer.Equalizer;
  export import FrequencyAnalyser = frequencyAnalyser.FrequencyAnalyser;
  export import WaveformAnalyser = waveformAnalyser.WaveformAnalyser;
  export import SpectrogramAnalyser = spectrogramAnalyser.SpectrogramAnalyser;
}
