import { FlowConnect } from "flow-connect";
import { Source } from "./source.js";
import { Destination } from "./destination.js";
import { Automate } from "./automate.js";
import { ChannelSplitter } from "./channel-splitter.js";
import { Debug } from "./debug.js";
import { ChannelMerger } from "./channel-merger.js";
import { ADSR } from "./adsr.js";
import { Gain } from "./gain.js";
import { Metronome } from "./metronome.js";
import { MoogEffect } from "./moog.js";
import { BitcrusherEffect } from "./bitcrusher.js";
import { BiquadFilter } from "./biquad-filter.js";
import { DelayEffect } from "./delay.js";
import { DynamicsCompressor } from "./dynamics-compressor.js";
import { ChorusEffect } from "./chorus.js";
import { OverdriveEffect } from "./overdrive.js";
import { AudioBufferSource } from "./audio-buffer-source.js";
import { Convolver } from "./convolver.js";
import { TremoloEffect } from "./tremolo.js";
import { PingPongEffect } from "./ping-pong-delay.js";
import { StereoPanner } from "./stereo-panner.js";
import { SpatialPanner } from "./spatial-panner.js";
import { Noise } from "./noise.js";
import { Oscillator } from "./oscillator.js";
import { Microphone } from "./microphone.js";
import { Distorter } from "./distorter.js";
import { Equalizer } from "./equalizer.js";
import { FrequencyAnalyser } from "./frequency-analyser.js";
import { WaveformAnalyser } from "./waveform-analyser.js";
import { SpectrogramAnalyser } from "./spectrogram-analyser.js";

FlowConnect.register<"node">({ type: "node", name: "audio/source" }, Source);
FlowConnect.register<"node">({ type: "node", name: "audio/destination" }, Destination);
FlowConnect.register<"node">({ type: "node", name: "audio/automate" }, Automate);
FlowConnect.register<"node">({ type: "node", name: "audio/channel-splitter" }, ChannelSplitter);
FlowConnect.register<"node">({ type: "node", name: "audio/debug" }, Debug);
FlowConnect.register<"node">({ type: "node", name: "audio/channel-merger" }, ChannelMerger);
FlowConnect.register<"node">({ type: "node", name: "audio/adsr" }, ADSR);
FlowConnect.register<"node">({ type: "node", name: "audio/gain" }, Gain);
FlowConnect.register<"node">({ type: "node", name: "audio/metronome" }, Metronome);
FlowConnect.register<"node">({ type: "node", name: "audio/moog" }, MoogEffect);
FlowConnect.register<"node">({ type: "node", name: "audio/bitcrusher" }, BitcrusherEffect);
FlowConnect.register<"node">({ type: "node", name: "audio/biquad" }, BiquadFilter);
FlowConnect.register<"node">({ type: "node", name: "audio/delay" }, DelayEffect);
FlowConnect.register<"node">({ type: "node", name: "audio/dynamics-compressor" }, DynamicsCompressor);
FlowConnect.register<"node">({ type: "node", name: "audio/chorus" }, ChorusEffect);
FlowConnect.register<"node">({ type: "node", name: "audio/overdrive" }, OverdriveEffect);
FlowConnect.register<"node">({ type: "node", name: "audio/buffer-source" }, AudioBufferSource);
FlowConnect.register<"node">({ type: "node", name: "audio/convolver" }, Convolver);
FlowConnect.register<"node">({ type: "node", name: "audio/tremolo" }, TremoloEffect);
FlowConnect.register<"node">({ type: "node", name: "audio/pingpong" }, PingPongEffect);
FlowConnect.register<"node">({ type: "node", name: "audio/stereo-panner" }, StereoPanner);
FlowConnect.register<"node">({ type: "node", name: "audio/spatial-panner" }, SpatialPanner);
FlowConnect.register<"node">({ type: "node", name: "audio/noise" }, Noise);
FlowConnect.register<"node">({ type: "node", name: "audio/oscillator" }, Oscillator);
FlowConnect.register<"node">({ type: "node", name: "audio/microphone" }, Microphone);
FlowConnect.register<"node">({ type: "node", name: "audio/distorter" }, Distorter);
FlowConnect.register<"node">({ type: "node", name: "audio/equalizer" }, Equalizer);
FlowConnect.register<"node">({ type: "node", name: "audio/frequency" }, FrequencyAnalyser);
FlowConnect.register<"node">({ type: "node", name: "audio/waveform" }, WaveformAnalyser);
FlowConnect.register<"node">({ type: "node", name: "audio/spectrogram" }, SpectrogramAnalyser);
