import { FlowConnect } from "flow-connect";
import { Timer } from "./timer.js";
import { Log } from "./log.js";
import { Buffer } from "./buffer.js";
import { ToArray } from "./to-array.js";
import { ArrayIndex } from "./array-index.js";
import { ArraySource } from "./array-source.js";
import { Random } from "./random.js";
import { BooleanSource } from "./boolean-source.js";
import { JsonSource } from "./json-source.js";
import { NumberSource } from "./number-source.js";
import { StringSource } from "./string-source.js";
import { FileSource } from "./file-source.js";
import { Compare } from "./compare.js";
import { Property } from "./property.js";
import { SyncEvent } from "./sync-event.js";
import { SyncData } from "./sync-data.js";
import { Delay } from "./delay.js";
import { ToVector } from "./to-vector.js";
import { NumberRange } from "./number-range.js";
import { GlobalEvent } from "./global-event.js";

FlowConnect.register<"node">({ type: "node", name: "common/timer" }, Timer);
FlowConnect.register<"node">({ type: "node", name: "common/log" }, Log);
FlowConnect.register<"node">({ type: "node", name: "common/buffer" }, Buffer);
FlowConnect.register<"node">({ type: "node", name: "common/to-array" }, ToArray);
FlowConnect.register<"node">({ type: "node", name: "common/array-index" }, ArrayIndex);
FlowConnect.register<"node">({ type: "node", name: "common/array-source" }, ArraySource);
FlowConnect.register<"node">({ type: "node", name: "common/random" }, Random);
FlowConnect.register<"node">({ type: "node", name: "common/boolean-source" }, BooleanSource);
FlowConnect.register<"node">({ type: "node", name: "common/json-source" }, JsonSource);
FlowConnect.register<"node">({ type: "node", name: "common/number-source" }, NumberSource);
FlowConnect.register<"node">({ type: "node", name: "common/string-source" }, StringSource);
FlowConnect.register<"node">({ type: "node", name: "common/file-source" }, FileSource);
FlowConnect.register<"node">({ type: "node", name: "common/compare" }, Compare);
FlowConnect.register<"node">({ type: "node", name: "common/property" }, Property);
FlowConnect.register<"node">({ type: "node", name: "common/sync-event" }, SyncEvent);
FlowConnect.register<"node">({ type: "node", name: "common/sync-data" }, SyncData);
FlowConnect.register<"node">({ type: "node", name: "common/delay" }, Delay);
FlowConnect.register<"node">({ type: "node", name: "common/to-vector" }, ToVector);
FlowConnect.register<"node">({ type: "node", name: "common/number-range" }, NumberRange);
FlowConnect.register<"node">({ type: "node", name: "common/global-event" }, GlobalEvent);
