name: Package-Audio

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/audio/**"
  push:
    branches: [main]
    paths:
      - "packages/audio/**"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm i
          lerna run --scope "@flow-connect/audio" build --stream
