name: Package-Common

on:
  pull_request:
    branches: [master]
    paths:
      - 'packages/common/**'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm i
          lerna run --scope "@flow-connect/common" build --stream
